name: CI - TypeScript & ESLint Check

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main, dev ]

env:
  NODE_VERSION: '18'

jobs:
  lint-and-type-check:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install root dependencies
        run: npm ci
        
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci
        
      - name: Run frontend linting
        working-directory: ./frontend
        run: npm run lint
        
      - name: Run backend linting
        working-directory: ./backend
        run: npm run lint
        continue-on-error: true
        
      - name: Run TypeScript type check
        working-directory: ./frontend
        run: npx tsc --noEmit
        
      - name: Run all checks
        run: npm run check-all
        
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-and-type-check
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ../backend && npm ci
          
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false --coverage --passWithNoTests
        continue-on-error: true
        
      - name: Run backend tests
        working-directory: ./backend
        run: npm test
        continue-on-error: true 